# Generated by Django 3.1.1 on 2020-10-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='empid',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='image',
            field=models.ImageField(default='', upload_to='static/'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='register',
            table='register',
        ),
    ]
